const products=[
 {name:'Destiny Heavyweight Hoodie',price:300,tag:'NEW',image:'andile.jpg/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=700&q=85'},
 {name:'D-01 Signature Tee',price:699,tag:'BEST SELLER',image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=700&q=85'},
 {name:'Concrete Cargo Pant',price:1499,tag:'NEW',image:'https://images.unsplash.com/photo-1506629905607-d405b7a30db9?auto=format&fit=crop&w=700&q=85'},
 {name:'Nocturne Varsity Jacket',price:2199,tag:'LIMITED',image:'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=700&q=85'}
];
let cart=[],wishlist=0,fit=[];const money=n=>'R'+n.toLocaleString('en-ZA');
const grid=document.querySelector('#productGrid');grid.innerHTML=products.map((p,i)=>`<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}"><span class="product-tag">${p.tag}</span><button class="wish" data-wish="${i}" aria-label="Add to wishlist">♡</button></div><div class="product-info"><h3>${p.name}</h3><strong>${money(p.price)}</strong><p>Oversized fit</p></div><button class="button quick" data-add="${i}">Add to bag</button></article>`).join('');
function showToast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function updateCart(){let count=cart.length,total=cart.reduce((a,p)=>a+p.price,0);document.querySelectorAll('.bag b').forEach(x=>x.textContent=count);document.querySelector('#cartCountTitle').textContent=`(${count})`;document.querySelector('#subtotal').textContent=money(total);document.querySelector('#cartItems').innerHTML=count?cart.map((p,i)=>`<div class="cart-row"><img src="${p.image}" alt=""><div><h3>${p.name}</h3><p>One size / Black</p><button data-remove="${i}">Remove</button></div><strong>${money(p.price)}</strong></div>`).join(''):'<p class="empty">Your bag is waiting for a direction.</p>'}
document.addEventListener('click',e=>{let add=e.target.closest('[data-add]');if(add){cart.push(products[add.dataset.add]);updateCart();showToast('Added to your bag');}let wish=e.target.closest('[data-wish]');if(wish){wish.textContent=wish.textContent==='♡'?'♥':'♡';wishlist+=wish.textContent==='♥'?1:-1;document.querySelector('.wishlist-btn b').textContent=wishlist}let remove=e.target.closest('[data-remove]');if(remove){cart.splice(remove.dataset.remove,1);updateCart()}});
const overlay=document.querySelector('#overlay');function open(panel){document.querySelector('#'+panel).classList.add('open');overlay.classList.add('active')}function closeAll(){document.querySelectorAll('.cart-panel,.fit-panel').forEach(x=>x.classList.remove('open'));overlay.classList.remove('active')}
document.querySelector('#cartBtn').onclick=()=>open('cartPanel');document.querySelector('#openFit').onclick=()=>open('fitPanel');document.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeAll);overlay.onclick=closeAll;
const options=[['D-01 Cap',499],['Obsidian Hoodie',1299],['Signature Tee',699],['Concrete Cargo',1499],['Terrain Sneaker',1599],['Steel Chain',399]];document.querySelector('#fitOptions').innerHTML=options.map((o,i)=>`<button class="fit-option" data-fit="${i}">${o[0]}<small>${money(o[1])}</small></button>`).join('');
document.querySelector('#fitOptions').onclick=e=>{let b=e.target.closest('[data-fit]');if(!b)return;let i=+b.dataset.fit;b.classList.toggle('active');fit=fit.some(x=>x.name===options[i][0])?fit.filter(x=>x.name!==options[i][0]):[...fit,{name:options[i][0],price:options[i][1],image:products[i%products.length].image}];document.querySelector('#fitPrice').textContent=money(fit.reduce((a,x)=>a+x.price,0))};
document.querySelector('#addFit').onclick=()=>{if(!fit.length)return showToast('Choose your pieces first');cart.push(...fit);updateCart();closeAll();showToast('Your complete look is in the bag')};
document.querySelector('#notifyBtn').onclick=()=>showToast('You’re on the early-access list.');document.querySelector('#newsletterForm').onsubmit=e=>{e.preventDefault();e.target.reset();showToast('Welcome to the movement. Check your inbox.')};
window.addEventListener('scroll',()=>document.querySelector('#nav').classList.toggle('scrolled',scrollY>50));
const launch=Date.now()+((3*24+14)*60+56)*60000;setInterval(()=>{let s=Math.max(0,launch-Date.now())/1000;document.querySelector('#days').textContent=String(Math.floor(s/86400)).padStart(2,'0');document.querySelector('#hours').textContent=String(Math.floor(s%86400/3600)).padStart(2,'0');document.querySelector('#minutes').textContent=String(Math.floor(s%3600/60)).padStart(2,'0')},1000);
document.querySelector('#menuBtn').onclick=()=>showToast('Explore the collection by scrolling down.');
